services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    networks:
      - picverse-network
    volumes:
      - mongo-primary-data:/data/db

  mongo-secondary:
    image: mongo:latest
    container_name: mongo-secondary
    command: ["--replSet", "rs0"]
    ports:
      - "27018:27017"
    networks:
      - picverse-network
    volumes:
      - mongo-secondary-data:/data/db

  mongo-arbiter:
    image: mongo:latest
    container_name: mongo-arbiter
    command: ["--replSet", "rs0"]
    ports:
      - "27019:27017"
    networks:
      - picverse-network
    volumes:
      - mongo-arbiter-data:/data/db

  # init-replica-set:
  #   image: mongo:latest
  #   container_name: init-replica-set
  #   depends_on:
  #     - mongo-primary
  #     - mongo-secondary
  #     - mongo-arbiter
  #   volumes:
  #     - ./init-replica.js:/init-replica.js
  #   entrypoint: >
  #     bash -c "
  #       sleep 30;
  #       mongosh --host mongo-write:27017 --eval 'load(\"/init-replica.js\");'
  #       echo 'Replica set init success';
  #     "
  #   networks:
  #     - picverse-network

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - picverse-network

  picverse-server:
    container_name: picverse-server
    build:
      context: ./picverse-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - picverse-network
    depends_on:
      - mongo-primary
      - mongo-secondary
      - mongo-arbiter
      - redis-cache
    environment:
      - REDIS_URL=redis://redis-cache:6379
      - MONGO_URI=mongodb://mongo-primary:27017,picverse-mongo-secondary:27017,mongo-arbiter:27017/picverse?replicaSet=rs0

  picverse-web:
    container_name: picverse-web
    build:
      context: ./picverse-web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - picverse-server
    networks:
      - picverse-network

volumes:
  mongo-primary-data:
  mongo-secondary-data:
  mongo-arbiter-data:

networks:
  picverse-network:
