export const CLOUDINARY_API_BASE_URL: string = process.env.NEXT_PUBLIC_CLOUDINARY_API_BASE_URL;
export const CLOUDINARY_API_KEY: string = process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY;
export const CLOUDINARY_UPLOAD_PRESET: string = process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;
