export const CLOUDINARY_API_BASE_URL = process.env.NEXT_PUBLIC_CLOUDINARY_API_BASE_URL;
export const CLOUDINARY_API_KEY = process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET = process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET;
export const CLOUDINARY_UPLOAD_PRESET = process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;
export const ACCESS_TOKEN_PREFIX = process.env.NEXT_PUBLIC_ACCESS_TOKEN_PREFIX;
export const REFRESH_TOKEN_PREFIX = process.env.NEXT_PUBLIC_REFRESH_TOKEN_PREFIX;
export const SERVER_ORIGIN = process.env.NEXT_PUBLIC_API_SERVER_ORIGIN;
export const BASE_URL = `${process.env.NEXT_PUBLIC_API_SERVER_ORIGIN}/api`;
