export enum QueryKeys {
  AUTHORIZE_CLIENT = "get-account",
  CLIENT_SECRET = "get-client-secret",
  RESOURCES = "get-resources",
  EXTERNAL_LINK_STATUS = "get-external-link-status",
  PROFILE = "get-profile",
  ACCESS_RECORDS = "get-access-records",
  CONVERSATIONS = "conversations",
  MESSAGES = "messages",
  FEEDS = "feeds",
  SIMILAR_PINS = "SIMILAR_PINS",
  SEARCH_TRENDING = "SEARCH_TRENDING",
  SEARCH_HISTORY = "SEARCH_HISTORY",
  SEARCH = "SEARCH",
  NOTIFICATIONS = "NOTIFICATIONS",
  PIN_DETAIL = "PIN_DETAIL",
  PIN_COMMENTS = "PIN_COMMENTS",
}

export enum MutationKeys {
  SIGN_UP = "sign-up",
  SIGN_IN = "sign-in",
  GOOGLE_SIGN_IN = "google-sign-in",
  SIGN_OUT = "sign-out",
  UPLOAD_FILE = "upload-file",
  CREATE_FOLDER = "create-folder",
  UPDATE_RESOURCE = "update-resource",
  DELETE_FILE = "delete-file",
  DELETE_FOLDER = "delete-folder",
  LINK_EXTERNAL_STORAGE = "link-external-storage",
  FORGOT_PASSWORD = "forgot-password",
  RESET_PASSWORD = "reset-password",
  CHANGE_PASSWORD = "change-password",
  UPDATE_PROFILE = "update-profile",
  UPLOAD_CLD_IMAGE = "upload-cld-image",
  DELETE_CLD_IMAGE = "delete-cld-image",
  SEARCH = "SEARCH",
}
