name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/picverse

            # force pull lastest version
            git reset --hard
            git stash
            git pull origin dev

            # stop running containers
            docker-compose down || true
            docker rm picverse-server || true
            docker rm picverse-web || true

            docker-compose up --build -d

            echo "Verifying container status..."
            docker ps

      - name: Notify success
        run: echo "Deployment completed successfully."